# Generated by Django 5.0.3 on 2024-03-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
