# Generated by Django 5.0.3 on 2024-03-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_userprofile_image_userprofile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.CharField(default='https://res.cloudinary.com/rishabh-insta/image/upload/v1711364015/media/y4kp4jeyxpfzhtud1mtg.png', max_length=255),
        ),
    ]
